### PR TITLE
GSOC 2023

### PR DESCRIPTION
**Pull request by samriddhi99**
I left out 'assembly' as I couldn't find it in the scoreset, and I also saw that it wasn't used much in the code further. I hope that is okay.

### CODE REVIEW

**Comment by ahwagner** [comment]
Hey @samriddhi99. I just reviewed. One thing that immediately jumps out at me is that this method is querying the live MaveDB API; but presumably any experiment metadata would simply be passed to the package you are writing. In other words, if someone were to submit data to MaveDB, the server would take those data and process them by sending the dataset directly to the package you are writing to validate and map the contents, then return the mapped dataset for ingest and storage in MaveDB (or elsewhere). You should not have to reference MaveDB or any other MAVE repository.

A good first step would be to start with an example input file. @jarbesfeld do we have any downloaded (unprocessed) MaveDB scoresets we can share with Samriddi for this purpose?

**Comment by jarbesfeld** [comment]
@samriddhi99 @ahwagner The unprocessed MaveDB score sets can be downloaded from the following endpoint in the MaveDB API: https://api.mavedb.org/docs#/score%20sets/get_score_set_scores_csv_api_v1_score_sets__urn__scores_get (in addition to being directly downloaded from the MaveDB website). I've attached score set 108-a-1- please let me know if there are other example score sets that would be useful!
[urn_mavedb_00000108-a-1_scores (1).csv](https://github.com/ave-dcd/dcd_mapping/files/11840372/urn_mavedb_00000108-a-1_scores.1.csv)

**Comment by ahwagner** [comment]
Thanks @jarbesfeld!

@samriddhi99 also see the experiment data associated with that scoreset, which is available as JSON here: https://api.mavedb.org/api/v1/experiments/urn%3Amavedb%3A00000108-a

@afrubin, should we have Samriddhi thinking about the current MaveDB format or the recent minimum information format at https://github.com/ave-dcd/mave_vocabulary for experiment data?

**Comment by afrubin** [comment]
The mapping process shouldn't need to care too much about the experiment metadata that are described in the mave_vocabulary repo so I think we can come back to this later.

One thing that will need to be reflected in the mapping software is the upcoming change from reference genomes/reference map objects to NCBI taxonmy IDs as described in this issue: https://github.com/VariantEffect/mavedb-api/issues/10

There are some files in there that will be helpful, including the format of the data that MaveDB will store as well as the taxonomy IDs for all published MaveDB score sets.

**Comment by samriddhi99** [comment]
Hi,

I wanted to clarify a few points and seek your feedback.
I'll be using the files I can download from here: https://api.mavedb.org/docs#/score%20sets/show_score_set_api_v1_score_sets__urn__get . Based on that, I'll treat the inputs as JSON files rather than a string of the URN.
Example input file: 
[response_1687590268578.json.txt](https://github.com/ave-dcd/dcd_mapping/files/11856375/response_1687590268578.json.txt)


Previously, I was using 'referencemaps'[0]['organismName'] for the organism name. But, due to the changes in MaveDB, I plan to use something like ['taxon_object']['organism_name'] (the way it will be implemented in MaveDB).

I would appreciate it if you could review my thought process and provide your feedback. Let me know if you have any suggestions or if there's anything else I should consider.

Thank you!

**Comment by ahwagner** [comment]
Your objective for the package should be to abstract this method so it can be hooked in however. Think about what the data are that you want to pass (e.g. a target sequence), and write Python functions that accept those data and perform the expected operations on them.

Your example file only needs to contain whatever data you need, in any minimal format you think would be helpful for this. So you might consider pruning the above response file into some minimal JSON data to inform the mapping process, and then describing that format as part of this package. The MaveDB server would then prepare these files and pass them to your method.

**Pull request closed without merging**
